# Generated by Django 5.2.1 on 2025-05-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
