# Generated by Django 5.2.1 on 2025-05-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_avaliable"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="photos",
            field=models.ImageField(default="covers/default.jpg", upload_to="covers/"),
        ),
    ]
