# Generated by Django 5.2.1 on 2025-05-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
    ]
