# Generated by Django 5.2.1 on 2025-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('books', '0002_book_avaliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuser',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='Borrowed', to='books.book'),
        ),
    ]
