# Generated by Django 5.2.1 on 2025-05-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_uuser_favorite_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uuser',
            old_name='favorite_books',
            new_name='borrowed_books',
        ),
    ]
