# Generated by Django 5.2.1 on 2025-05-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_favorite_books_uuser_borrowed_books'),
        ('books', '0004_remove_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuser',
            name='reserved_books',
            field=models.ManyToManyField(blank=True, related_name='Reserved', to='books.book'),
        ),
    ]
